name: 'Terraform GitHub Actions'
on:
 - pull_request
 - push

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: terraform-fmt
      uses: hashicorp/terraform-github-actions/fmt@2.298.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
    - name: terraform-init
      uses: hashicorp/terraform-github-actions/init@2.298.2
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         TF_ACTION_WORKING_DIR: .
    - name: terraform-validate
      uses: hashicorp/terraform-github-actions/validate@2.298.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
    - name: terraform-plan
      uses: hashicorp/terraform-github-actions/plan@2.298.2
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
          TF_ACTION_WORKSPACE: default
