name: 'Terraform GitHub Actions'
on:
 - pull_request
 - push

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
    - name: checkout 
    - uses: actions/checkout@master

    - name: terraform-fmt
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 0.5.0
          tf_action_subcommad: "format"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
    
    - name: terraform-init
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 0.5.0
          tf_action_subcommad: "init"
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         TF_ACTION_WORKING_DIR: .
         
    - name: terraform-validate
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 0.5.0
          tf_action_subcommad: "Validate"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
          
    - name: terraform-plan
      uses: hashicorp/terraform-github-actions@master
      with:
          tf_actions_version: 0.5.0
          tf_action_subcommad: "plan"
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TF_ACTION_WORKING_DIR: .
          TF_ACTION_WORKSPACE: default
